# Create ubuntu as base image
FROM ubuntu

# Install packages
RUN apt-get -y update
RUN apt-get install -y iputils-ping
RUN apt-get install -y net-tools
RUN apt-get install -y dsniff
RUN apt-get install -y tcpdump
RUN apt-get install -y netcat
